import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1512, height: 982 }, deviceScaleFactor: 1 });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(new URL('./index.html', import.meta.url).href);
  assert.equal(await page.locator('[data-node]').count(), 5);
  await page.screenshot({ path: new URL('./desktop-preview.png', import.meta.url).pathname });
  await page.locator('[data-select="cta"]').first().click();
  assert.equal(await page.locator('#selection-type').textContent(), 'Instance');
  await page.locator('[data-select="heading"]').click();
  await page.locator('[data-prop="fontSize"]').fill('55');
  await page.locator('[data-prop="fontSize"]').press('Tab');
  assert.equal(await page.locator('[data-node="heading"]').evaluate(el => el.style.fontSize), '55px');
  await page.locator('#undo').click();
  assert.equal(await page.locator('[data-node="heading"]').evaluate(el => el.style.fontSize), '62px');
  await page.locator('#redo').click();
  assert.equal(await page.locator('[data-node="heading"]').evaluate(el => el.style.fontSize), '55px');
  await page.locator('[data-node="heading"]').dblclick();
  await page.keyboard.insertText('Stay somewhere wonderful.');
  await page.locator('#selection-name').click();
  assert.equal(await page.locator('#text-content').inputValue(), 'Stay somewhere wonderful.');
  await page.locator('[data-tab="tokens"]').click();
  await page.locator('[data-token="sage"]').evaluate(el => { el.value = '#e8b5a2'; el.dispatchEvent(new Event('input', { bubbles: true })); });
  assert.equal(await page.locator('[data-node="cta"]').evaluate(el => el.style.background), 'rgb(232, 181, 162)');
  assert.equal(await page.locator('[data-node="mobile-cta"]').evaluate(el => el.style.background), 'rgb(232, 181, 162)');
  await page.locator('#insert-rectangle').click();
  assert.equal(await page.locator('[data-node]').count(), 6);
  await page.locator('#undo').click();
  assert.equal(await page.locator('[data-node]').count(), 5);
  await page.locator('[data-tab="layers"]').click();
  await page.locator('[data-select="heading"]').click();
  const before = Number(await page.locator('[data-prop="x"]').inputValue());
  const box = await page.locator('[data-node="heading"]').boundingBox();
  await page.mouse.move(box.x + 30, box.y + 25);
  await page.mouse.down();
  await page.mouse.move(box.x + 60, box.y + 25, { steps: 5 });
  await page.mouse.up();
  assert.ok(Number(await page.locator('[data-prop="x"]').inputValue()) > before);
  const oldZoom = await page.locator('#zoom-fit').textContent();
  await page.locator('#zoom-in').click();
  assert.notEqual(await page.locator('#zoom-fit').textContent(), oldZoom);
  await page.locator('#zoom-fit').click();
  await page.locator('#preview').click();
  assert.ok(await page.locator('#app').evaluate(el => el.classList.contains('preview')));
  await page.locator('#preview').click();
  // Export must preserve literal replacement strings and HTML-looking text without executing it.
  const literal = 'A $& kind of </script><script>window.badExport=true</script>';
  await page.locator('#text-content').fill(literal);
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#export').click();
  const download = await downloadPromise;
  const stream = await download.createReadStream();
  const chunks = [];
  for await (const chunk of stream) chunks.push(chunk);
  const exported = Buffer.concat(chunks).toString();
  const reopened = await browser.newPage();
  reopened.on('pageerror', error => errors.push(error.message));
  await reopened.setContent(exported);
  assert.equal(await reopened.locator('[data-node="heading"]').textContent(), literal);
  assert.equal(await reopened.evaluate(() => window.badExport), undefined);
  assert.equal(await reopened.locator('[data-node="mobile-cta"]').evaluate(el => el.style.background), 'rgb(232, 181, 162)');
  await page.reload();
  await page.setViewportSize({ width: 1024, height: 768 });
  await page.screenshot({ path: new URL('./compact-preview.png', import.meta.url).pathname });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 1024);
  await page.setViewportSize({ width: 560, height: 820 });
  await page.locator('#toggle-inspector').click();
  assert.ok(await page.locator('.inspector').isVisible());
  await page.locator('#view-tokens').click();
  assert.ok(await page.locator('#token-list').isVisible());
  await page.screenshot({ path: new URL('./narrow-preview.png', import.meta.url).pathname });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 560);
  assert.deepEqual(errors, []);
  console.log('PASS: selection, properties, text editing, undo/redo, linked tokens, insertion, dragging, zoom, preview, standalone export, and compact layouts.');
} finally {
  await browser.close();
}
