import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1512, height: 982 }, deviceScaleFactor: 1 });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(new URL('./index.html', import.meta.url).href);
  assert.equal(await page.locator('[data-node]').count(), 5);
  assert.equal(await page.locator('.workspace-bar').count(), 0);
  assert.equal(await page.locator('header').count(), 1);
  assert.ok(await page.locator('.left-panel #project-info').isVisible());
  assert.ok(await page.locator('.inspector #design-mode').isVisible());
  assert.ok(await page.locator('#canvas #zoom-fit').isVisible());
  assert.equal((await page.locator('#canvas').boundingBox()).y, 32);
  await page.locator('#project-info').click();
  assert.ok(await page.locator('#modal').isVisible());
  await page.locator('#dismiss-modal').click();
  await page.locator('.inspector [data-future="prototype"]').click();
  assert.ok(await page.locator('#modal').isVisible());
  await page.locator('#dismiss-modal').click();

  assert.equal(await page.locator('html').getAttribute('data-layout'), 'docked');
  assert.equal(await page.locator('html').getAttribute('data-accent'), 'honey');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  assert.equal(await page.locator('.left-panel').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(32, 30, 26)');
  assert.equal(await page.locator('body').evaluate(el => getComputedStyle(el).fontFamily.split(',')[0]), '"Hanken Grotesk"');
  assert.ok(await page.evaluate(() => document.fonts.check('12px "Hanken Grotesk"')));
  const canvasOffset = () => page.locator('#world').evaluate(el => {
    const matrix = new DOMMatrix(getComputedStyle(el).transform);
    return { x: matrix.e, y: matrix.f };
  });
  const layerState = () => page.locator('[data-node]').evaluateAll(nodes => nodes.map(el => ({
    id: el.dataset.node, selected: el.classList.contains('selected'), left: el.style.left, top: el.style.top, text: el.innerText,
  })));
  const originalLayers = await layerState();
  for (const target of ['background', 'photo', 'heading']) {
    const area = await page.locator(target === 'background' ? '#canvas' : `[data-node="${target}"]`).boundingBox();
    const x = area.x + 65, y = area.y + 55;
    const offset = await canvasOffset();
    await page.mouse.move(x, y);
    await page.mouse.down({ button: 'middle' });
    assert.ok(await page.locator('#canvas').evaluate(el => el.classList.contains('panning')));
    await page.mouse.move(x + 80, y + 45, { steps: 5 });
    await page.mouse.up({ button: 'middle' });
    const moved = await canvasOffset();
    assert.ok(Math.abs(moved.x - offset.x - 80) < 0.1);
    assert.ok(Math.abs(moved.y - offset.y - 45) < 0.1);
    assert.deepEqual(await layerState(), originalLayers);
    assert.ok(await page.locator('#undo').isDisabled());
    assert.ok(await page.locator('[data-tool="select"]').evaluate(el => el.classList.contains('active')));
    assert.equal(await page.locator('#canvas').evaluate(el => el.classList.contains('panning')), false);
    await page.mouse.move(x + 100, y + 60);
    assert.deepEqual(await canvasOffset(), moved);
    await page.locator('#zoom-fit').click();
  }
  // Pointer capture keeps panning alive over the inspector; release ends it there.
  const canvasBounds = await page.locator('#canvas').boundingBox();
  await page.mouse.move(canvasBounds.x + canvasBounds.width - 20, canvasBounds.y + 60);
  await page.mouse.down({ button: 'middle' });
  const boundaryOffset = await canvasOffset();
  await page.mouse.move(canvasBounds.x + canvasBounds.width + 40, canvasBounds.y + 80, { steps: 4 });
  await page.mouse.up({ button: 'middle' });
  assert.ok(Math.abs((await canvasOffset()).x - boundaryOffset.x - 60) < 0.1);
  assert.equal(await page.locator('#canvas').evaluate(el => el.classList.contains('panning')), false);
  await page.locator('#zoom-fit').click();
  // Text-editing mode remains intact, and losing window focus cancels an active pan.
  await page.locator('[data-node="heading"]').dblclick();
  const editingBox = await page.locator('[data-node="heading"]').boundingBox();
  await page.mouse.move(editingBox.x + 30, editingBox.y + 25);
  await page.mouse.down({ button: 'middle' });
  await page.mouse.move(editingBox.x + 55, editingBox.y + 40, { steps: 3 });
  assert.equal(await page.locator('[data-node="heading"]').getAttribute('contenteditable'), 'true');
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  const blurredOffset = await canvasOffset();
  await page.mouse.move(editingBox.x + 85, editingBox.y + 70);
  await page.mouse.up({ button: 'middle' });
  assert.deepEqual(await canvasOffset(), blurredOffset);
  assert.equal(await page.locator('#canvas').evaluate(el => el.classList.contains('panning')), false);
  await page.locator('#selection-name').click();
  await page.locator('#zoom-fit').click();
  await page.screenshot({ path: new URL('./desktop-preview.png', import.meta.url).pathname });
  await page.locator('[data-select="cta"]').first().click();
  assert.equal(await page.locator('#selection-type').textContent(), 'Instance');
  await page.locator('[data-select="heading"]').click();
  await page.locator('[data-prop="fontSize"]').fill('55');
  await page.locator('[data-prop="fontSize"]').press('Tab');
  assert.equal(await page.locator('[data-node="heading"]').evaluate(el => el.style.fontSize), '55px');
  await page.locator('#undo').click();
  assert.equal(await page.locator('[data-node="heading"]').evaluate(el => el.style.fontSize), '62px');
  await page.locator('#redo').click();
  assert.equal(await page.locator('[data-node="heading"]').evaluate(el => el.style.fontSize), '55px');
  await page.locator('[data-node="heading"]').dblclick();
  await page.keyboard.insertText('Stay somewhere wonderful.');
  await page.locator('#selection-name').click();
  assert.equal(await page.locator('#text-content').inputValue(), 'Stay somewhere wonderful.');
  // Appearance switches preserve the edited document across both layouts and all accents.
  await page.locator('#appearance-toggle').click();
  const brightnessContent = await page.locator('[data-node="heading"]').textContent();
  for (const value of [24, 30, 36]) {
    await page.locator(`[data-brightness="${value}"]`).click();
    assert.equal(await page.locator('.left-panel').evaluate(el => getComputedStyle(el).backgroundColor), `rgb(${value + 2}, ${value}, ${value - 4})`);
  }
  await page.locator('#panel-brightness').fill('20');
  assert.equal(await page.locator('.inspector').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(22, 20, 16)');
  await page.locator('#panel-brightness').press('ArrowRight');
  assert.equal(await page.locator('#panel-brightness').inputValue(), '21');
  await page.locator('#canvas-brightness').fill('14');
  assert.equal(await page.locator('#canvas').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(16, 14, 10)');
  assert.equal(await page.locator('[data-node="heading"]').textContent(), brightnessContent);
  assert.equal(await page.locator('[data-node="cta"]').evaluate(el => el.style.background), 'rgb(221, 231, 198)');
  assert.equal(await page.locator('.footer .accent-dot').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(210, 154, 68)');
  assert.equal(await page.locator('#export').evaluate(el => getComputedStyle(el).backgroundColor), 'rgba(0, 0, 0, 0)');
  await page.locator('[data-brightness="30"]').click();
  // Paper scheme swaps to Apiary's light tokens and parks the brightness controls.
  await page.locator('[data-scheme-choice="light"]').click();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
  assert.equal(await page.locator('.left-panel').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(255, 255, 255)');
  assert.equal(await page.locator('#canvas').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(245, 244, 241)');
  assert.equal(await page.locator('.footer .accent-dot').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(184, 132, 46)');
  assert.ok(await page.locator('#panel-brightness').isDisabled());
  assert.equal(await page.locator('[data-node="heading"]').textContent(), brightnessContent);
  await page.locator('[data-scheme-choice="dark"]').click();
  assert.ok(await page.locator('#panel-brightness').isEnabled());

  for (const layout of ['docked', 'floating']) {
    await page.locator(`[data-layout-choice="${layout}"]`).click();
    for (const accent of ['honey', 'amber', 'blue', 'sage', 'clay', 'lilac']) {
      await page.locator(`[data-accent-choice="${accent}"]`).click();
      assert.equal(await page.locator('html').getAttribute('data-accent'), accent);
      assert.equal(await page.locator('[data-node="heading"]').textContent(), 'Stay somewhere wonderful.');
      assert.equal(await page.locator('[data-node="cta"]').evaluate(el => el.style.background), 'rgb(221, 231, 198)');
    }
  }
  await page.locator('#panel-radius').fill('20');
  assert.equal(await page.locator('.left-panel').evaluate(el => getComputedStyle(el).borderRadius), '20px');
  const xBeforeRadiusKey = await page.locator('[data-prop="x"]').inputValue();
  await page.locator('#panel-radius').press('ArrowRight');
  assert.equal(await page.locator('[data-prop="x"]').inputValue(), xBeforeRadiusKey);
  await page.locator('#custom-accent').evaluate(el => { el.value = '#102030'; el.dispatchEvent(new Event('input', { bubbles: true })); });
  assert.equal(await page.locator('html').evaluate(el => el.style.getPropertyValue('--accent-ink')), '#ffffff');
  assert.equal(await page.locator('#accent-name').textContent(), 'Custom');
  await page.locator('#original-appearance').click();
  assert.equal(await page.locator('html').getAttribute('data-layout'), 'docked');
  assert.equal(await page.locator('html').getAttribute('data-accent'), 'honey');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  assert.ok(await page.locator('#panel-radius').isDisabled());
  await page.locator('[data-layout-choice="floating"]').click();
  await page.locator('[data-accent-choice="blue"]').click();
  await page.locator('#appearance-close').click();
  assert.ok(page.url().includes('panels=floating'));
  assert.ok(page.url().includes('accent=blue'));
  await page.locator('#appearance-toggle').click();
  await page.locator('#panel-brightness').fill('28');
  await page.locator('#canvas-brightness').fill('18');
  await page.locator('#appearance-close').click();
  await page.locator('[data-tab="tokens"]').click();
  await page.locator('[data-token="sage"]').evaluate(el => { el.value = '#e8b5a2'; el.dispatchEvent(new Event('input', { bubbles: true })); });
  assert.equal(await page.locator('[data-node="cta"]').evaluate(el => el.style.background), 'rgb(232, 181, 162)');
  assert.equal(await page.locator('[data-node="mobile-cta"]').evaluate(el => el.style.background), 'rgb(232, 181, 162)');
  await page.locator('#insert-rectangle').click();
  assert.equal(await page.locator('[data-node]').count(), 6);
  await page.locator('#undo').click();
  assert.equal(await page.locator('[data-node]').count(), 5);
  await page.locator('[data-tab="layers"]').click();
  await page.locator('[data-select="heading"]').click();
  const before = Number(await page.locator('[data-prop="x"]').inputValue());
  const box = await page.locator('[data-node="heading"]').boundingBox();
  await page.mouse.move(box.x + 30, box.y + 25);
  await page.mouse.down();
  await page.mouse.move(box.x + 60, box.y + 25, { steps: 5 });
  await page.mouse.up();
  assert.ok(Number(await page.locator('[data-prop="x"]').inputValue()) > before);
  const oldZoom = await page.locator('#zoom-fit').textContent();
  await page.locator('#zoom-in').click();
  assert.notEqual(await page.locator('#zoom-fit').textContent(), oldZoom);
  await page.locator('#zoom-fit').click();
  // Hotkeys drive the dock; frame rows focus the camera while only the chevron collapses.
  await page.keyboard.press('h');
  assert.ok(await page.locator('[data-tool="hand"]').evaluate(el => el.classList.contains('active')));
  await page.keyboard.press('V');
  assert.ok(await page.locator('[data-tool="select"]').evaluate(el => el.classList.contains('active')));
  const beforeFocus = await canvasOffset();
  await page.locator('[data-collapse="mobile"]').click();
  assert.notDeepEqual(await canvasOffset(), beforeFocus);
  assert.equal(await page.locator('[data-collapse="mobile"]').getAttribute('aria-expanded'), 'true');
  await page.locator('[data-collapse="mobile"] .chevron-hit').click();
  assert.equal(await page.locator('[data-collapse="mobile"]').getAttribute('aria-expanded'), 'false');
  await page.locator('[data-collapse="mobile"] .chevron-hit').click();
  assert.equal(await page.locator('[data-collapse="mobile"]').getAttribute('aria-expanded'), 'true');
  await page.keyboard.press('f');
  assert.ok(await page.locator('#modal').isVisible());
  await page.locator('#dismiss-modal').click();
  await page.locator('#zoom-fit').click();
  await page.locator('#preview').click();
  assert.ok(await page.locator('#app').evaluate(el => el.classList.contains('preview')));
  await page.locator('#preview').click();
  // Export must preserve literal replacement strings and HTML-looking text without executing it.
  const literal = 'A $& kind of </script><script>window.badExport=true</script>';
  await page.locator('#text-content').fill(literal);
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#export').click();
  const download = await downloadPromise;
  const stream = await download.createReadStream();
  const chunks = [];
  for await (const chunk of stream) chunks.push(chunk);
  const exported = Buffer.concat(chunks).toString();
  const reopened = await browser.newPage();
  reopened.on('pageerror', error => errors.push(error.message));
  await reopened.setContent(exported);
  assert.equal(await reopened.locator('[data-node="heading"]').textContent(), literal);
  assert.equal(await reopened.evaluate(() => window.badExport), undefined);
  assert.equal(await reopened.locator('html').getAttribute('data-layout'), 'floating');
  assert.equal(await reopened.locator('html').getAttribute('data-accent'), 'blue');
  assert.ok(await reopened.locator('#appearance-popover').isHidden());
  assert.equal(await reopened.locator('html').getAttribute('data-panel-tone'), '28');
  assert.equal(await reopened.locator('html').getAttribute('data-canvas-tone'), '18');
  assert.equal(await reopened.locator('[data-node="mobile-cta"]').evaluate(el => el.style.background), 'rgb(232, 181, 162)');
  await page.reload();
  assert.equal(await page.locator('html').getAttribute('data-accent'), 'blue');
  assert.equal(await page.locator('html').getAttribute('data-panel-tone'), '28');
  await page.locator('#appearance-toggle').click();
  await page.locator('[data-scheme-choice="light"]').click();
  await page.screenshot({ path: new URL('./appearance-preview.png', import.meta.url).pathname });
  await page.locator('[data-scheme-choice="dark"]').click();
  await page.locator('#appearance-close').click();
  await page.setViewportSize({ width: 1024, height: 768 });
  await page.screenshot({ path: new URL('./compact-preview.png', import.meta.url).pathname });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 1024);
  await page.setViewportSize({ width: 560, height: 820 });
  await page.locator('#toggle-inspector').click();
  assert.ok(await page.locator('.inspector').isVisible());
  await page.locator('#view-tokens').click();
  assert.ok(await page.locator('#token-list').isVisible());
  await page.screenshot({ path: new URL('./narrow-preview.png', import.meta.url).pathname });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 560);
  assert.deepEqual(errors, []);
  console.log('PASS: Apiary tokens and fonts, charcoal/paper schemes, selection, properties, text editing, undo/redo, linked tokens, insertion, dragging, zoom, preview, standalone export, compact layouts, appearance combinations, URL state, custom colors, appearance export, middle-mouse panning, and the single-header layout.');
} finally {
  await browser.close();
}
